version: '3'
services:
  envoyapigw:
    build: ApiGateways/EnvoyApiGw/
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./ApiGateways/EnvoyApiGw/envoy.yaml:ect/envoy/envoy.yaml
      - ./ApiGateways/EnvoyApiGw/https.crt:ect/ssl/certs/https.crt
      - ./ApiGateways/EnvoyApiGw/key.pem:ect/ssl/certs/key.pem
  coffeeapi:
    build: Services/Coffee.Api/
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
  teaapi:
    build: Services/Tea.Api/
    ports:
      - "8082:80"
      - "8083:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8083"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

  